# Generated by Django 3.2.12 on 2023-01-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipe',
            field=models.CharField(choices=[('A', 'Aridos'), ('B', 'Mamposteria'), ('C', 'Griferia')], default='A', max_length=20, verbose_name='State'),
        ),
    ]
