# Generated by Django 3.2.12 on 2023-01-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_tipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=30, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.CharField(max_length=30, verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipe',
            field=models.CharField(choices=[('A', 'Aridos'), ('B', 'Mamposteria'), ('C', 'Griferia')], default='A', max_length=20, verbose_name='Tipo de Item'),
        ),
    ]
