version: '3'

services:
  db:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'stock_db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: '(y[]XK1xJo5,)%^'
       MYSQL_HOST: '127.0.0.1'
       MYSQL_PORT: '3306'
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db